# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:latest
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
       - postgresql-data:/var/lib/postgresql/data/
       - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB}      
      - POSTGRES_CONFIG_FILE=/etc/postgresql/postgresql.conf
    ports: 
      - 5432:5432
    # Info on how to tune: https://pankajconnect.medium.com/performance-tuning-postgresql-containers-in-a-docker-environment-89ca7090e072


  adminer:
    # Note that to contact postgresql you need to use the name of the container (db) as the servername instead of "localhost". 
    image: adminer
    restart: always
    ports:
      - 8070:8080
    depends_on:
      - db

  sqlpage:
    # see: https://github.com/lovasoa/SQLpage
    image: lovasoa/sqlpage
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:    
      - ./sqlpage/var/www:/var/www
      - ./sqlpage/etc/sqlpage:/etc/sqlpage
    environment:
      - SQLBASE_DATABASE_URL=postgres://postgres:example@db/postgres
#      - SQLBASE_DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db/${DB}


  # TODO: Add PostGREST
  

volumes:
  postgresql-data:
