# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:latest
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
       - postgresql-storage:/var/lib/postgresql
    env_file:
      - 'variables.env'
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB      
    ports: 
      - 5432:5432
    # Info on how to tune: https://pankajconnect.medium.com/performance-tuning-postgresql-containers-in-a-docker-environment-89ca7090e072


  adminer:
    # Note that to contact postgresql you need to use the name of the container (db) as the servername instead of "localhost". 
    image: adminer
    restart: always
    env_file:
      - 'variables.env'
    ports:
      - 8070:8070
    depends_on:
      - db

  sqlpage:
    image: lovasoa/sqlpage
    restart: always
    ports:
      - 8080:8080
    volumes:
    env_file:
      - 'variables.env'

  

volumes:
  postgresql-storage:
